- hosts: all
  tasks:
    -  package:
         name: "httpd"
         state: present
       when: ansible_os_family == "RedHat" or  ansible_memfree_mb >= 2048

    - debug:
        var: ansible_os_family
    - debug:
        var: ansible_memfree_mb
